# Generated by Django 5.0.6 on 2024-08-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance',
            field=models.JSONField(default=dict),
        ),
    ]
